# Generated by Django 4.0.2 on 2022-02-22 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_created_date_blogpost_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file', models.ImageField(height_field='height', upload_to='', verbose_name='Fichier photo', width_field='width')),
                ('height', models.IntegerField(verbose_name='Hauteur')),
                ('width', models.IntegerField(verbose_name='Largeur')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='main_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.photo'),
        ),
    ]
